// Generated by GLSLToC. Do no modify.

#include "Shaders.h"
#include "trivial.frag.h"
#include "trivial.vert.h"

const unsigned shader_count = 2;
const ShaderModule * const shaders[] = {
	&trivial_frag_shader,
	&trivial_vert_shader,
	nullptr
};
